package bank.account.transfer.entity;
// Generated May 4, 2021 6:28:25 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * BankAccount generated by hbm2java
 */
public class BankAccount extends AbstractBankAccount implements java.io.Serializable {

    private String accountNumber;
    private BigDecimal amount;

    public BankAccount() {
    }

    public BankAccount(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public BankAccount(String accountNumber, BigDecimal amount) {
        this.accountNumber = accountNumber;
        this.amount = amount;
    }

    public String getAccountNumber() {
        return this.accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Override
    public String toString() {
        return accountNumber + " :: " + amount.toPlainString(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof  BankAccount)) {
            return false;
        }
        BankAccount other = (BankAccount) obj;
        return accountNumber.equals(other.getAccountNumber());
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (accountNumber != null?accountNumber.hashCode():0);
        return hash;
    }

}
